# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the cumulative sum of each row in a matrix
#'
#' @param x A numeric matrix
#' @return A matrix containing the cumulative sum of each row of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' cumSumRow(a)
#' @export
cumSumRow <- function(x) {
    .Call('luxmatrix_cumSumRow', PACKAGE = 'luxmatrix', x)
}

#' Calculate the cumulative sum of each column in a matrix
#' @param x A numeric matrix
#' @return A matrix containing the cumulative product of each column of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' cumSumCol(a)
#' @export
cumSumCol <- function(x) {
    .Call('luxmatrix_cumSumCol', PACKAGE = 'luxmatrix', x)
}

#' Calculate the limited cumulative sum of each column in a matrix
#' @param x A numeric matrix
#' @param limits A vector showing the number of values to be added in each column, starting at the left side
#' @return A matrix containing the cumulative product of each column of the matrix \code{x}, with limited values in each row used
#' @examples
#' a <- matrix(1:9, 3)
#' sumColLimited(a, limits = c(1,2,3))
#' @export
sumColLimited <- function(x, limits) {
    .Call('luxmatrix_sumColLimited', PACKAGE = 'luxmatrix', x, limits)
}

#' Calculate the limited cumulative sum of each row in a matrix
#' @param x A numeric matrix
#' @param limits A vector showing the number of values to be added in each column, starting at the left side
#' @return A matrix containing the cumulative product of each column of the matrix \code{x}, with limited values in each row used
#' @examples
#' a <- matrix(1:9, 3)
#' sumRowLimited(a, limits = c(1,2,3))
#' @export
sumRowLimited <- function(x, limits) {
    .Call('luxmatrix_sumRowLimited', PACKAGE = 'luxmatrix', x, limits)
}

#' Calculate the product of each row in a matrix
#'
#' @param x A numeric matrix
#' @return A vector containing the product of each row of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' prodRow(a)
#' @export
prodRow <- function(x) {
    .Call('luxmatrix_prodRow', PACKAGE = 'luxmatrix', x)
}

#' Calculate the product of each column in a matrix
#'
#' @param x A numeric matrix
#' @return A vector containing the product of each column of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' prodCol(a)
#' @export
prodCol <- function(x) {
    .Call('luxmatrix_prodCol', PACKAGE = 'luxmatrix', x)
}

#' Calculate the cumulative product of each row in a matrix
#'
#' @param x A numeric matrix
#' @return A matrix containing the cumulative product of each row of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' cumProdRow(a)
#' @export
cumProdRow <- function(x) {
    .Call('luxmatrix_cumProdRow', PACKAGE = 'luxmatrix', x)
}

#' Calculate the cumulative product of each column in a matrix
#' @param x A numeric matrix
#' @return A matrix containing the cumulative product of each column of the matrix \code{x}
#' @examples
#' a <- matrix(1:9, 3)
#' cumProdCol(a)
#' @export
cumProdCol <- function(x) {
    .Call('luxmatrix_cumProdCol', PACKAGE = 'luxmatrix', x)
}

#' Calculate the limited cumulative product of each row in a matrix.
#' @param x A numeric matrix
#' @param limits A vector showing the number of values to be multiplied in each row, starting at the left side
#' @return A matrix containing the cumulative product of each row of the matrix \code{x}, with limited values in each row used
#' @examples
#' a <- matrix(1:9, 3)
#' prodRowLimited(a, c(1,2,3))
#' @export
prodRowLimited <- function(x, limits) {
    .Call('luxmatrix_prodRowLimited', PACKAGE = 'luxmatrix', x, limits)
}

#' Calculate the limited cumulative product of each column in a matrix
#' @param x A numeric matrix
#' @param limits A vector showing the number of values to be multiplied in each column, starting at the left side
#' @return A matrix containing the cumulative product of each column of the matrix \code{x}, with limited values in each row used
#' @examples
#' a <- matrix(1:9, 3)
#' prodColLimited(a, limits = c(1,2,3))
#' @export
prodColLimited <- function(x, limits) {
    .Call('luxmatrix_prodColLimited', PACKAGE = 'luxmatrix', x, limits)
}

#' Extract values from a matrix with uneven column offsets
#'
#' @param mat matrix from which to extract values
#' @param position starting position of extraction
#' @param width A scalar showing the number of values to extract
#' @param extensionMethod Method of extending the mat.  Options are \code{none (default), lastValue, extensionValue}:  the \code{width} must fit within mat; \code{lastValue} mat is extended with the last value of each row; \code{extensionValue} mat is extended with extensionValue
#' @param extensionValue used if \code{extensionMethod} is set to \code{extensionValue}
#' @return matrix of extracted values
#' @examples
#' a <- matrix(1:81, 3)
#' raggedExtract(mat=a, position = c(1,2,3), width = 3)
#' @export
raggedExtract <- function(mat, position, width, extensionMethod = "none", extensionValue = 0) {
    .Call('luxmatrix_raggedExtract', PACKAGE = 'luxmatrix', mat, position, width, extensionMethod, extensionValue)
}

repMatrixCpp <- function(vec, times, ncol) {
    .Call('luxmatrix_repMatrixCpp', PACKAGE = 'luxmatrix', vec, times, ncol)
}

